sudo: false

language: php

install:
  - export ACQUIA_JOB_START=$(date +%s)

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "vendor"

php:
  - 5.6
  - 7.1

services:
  - mysql

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE drupal;'
  - source ./scripts/travis/setup-environment.sh
  - bash -x ./scripts/travis/before-install.sh
  - bash -x ./scripts/travis/test-source-code.sh
  - drush --yes --verbose --debug --root=docroot site-install standard --db-url="mysql://root@127.0.0.1/drupal"
  - bash -x ./scripts/travis/install.sh
  - drush --yes --root=docroot en simpletest

script:
  - bash -x -e ./scripts/travis/run-tests.sh
